import React from "react";
import { useNavigate } from "react-router-dom";
import { Printer, Download, Activity, Plus } from "lucide-react";
import Layout from "../components/Layout.jsx";
import { useApp } from "../context/AppContext.jsx";
import { RiskBadge, PredictionBadge } from "../components/Atoms.jsx";

export default function ClinicalReport() {
  const { current, user } = useApp();
  const navigate = useNavigate();

  if (!current) {
    return (
      <Layout eyebrow="Clinical Report" title="No Prediction Selected">
        <div className="card card-pad" style={{ textAlign: "center", padding: 48 }}>
          <p style={{ color: "var(--muted)", marginBottom: 16, fontSize: 13.5 }}>
            Run a prediction to generate a printable clinical report.
          </p>
          <button className="btn btn-primary" onClick={() => navigate("/predict")}>
            <Plus size={16} /> Start New Prediction
          </button>
        </div>
      </Layout>
    );
  }

  const { patient, result, unified, shap, lime, summary, timestamp } = current;
  const topShap = shap.slice(0, 5);
  const topLime = lime.slice(0, 5);

  function handleExportPdf() {
    window.print();
  }

  return (
    <Layout
      eyebrow="Clinical Report"
      title="Diabetes Risk & Explainability Report"
      right={
        <button className="btn btn-primary" onClick={handleExportPdf}>
          <Download size={15} /> Export PDF
        </button>
      }
    >
      <div className="card card-pad" id="report-root" style={{ maxWidth: 880, margin: "0 auto" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 8 }}>
          <div style={{ display: "flex", gap: 12, alignItems: "center" }}>
            <div className="brand-mark" style={{ width: 40, height: 40 }}><Activity size={20} /></div>
            <div>
              <h2 style={{ fontSize: 17 }}>UnifyXAI-Med</h2>
              <p style={{ fontSize: 11, color: "var(--muted)" }}>A Unified Explainability Pipeline for Healthcare AI</p>
            </div>
          </div>
          <div style={{ textAlign: "right" }}>
            <p style={{ fontSize: 11.5, color: "var(--muted)" }}>Generated</p>
            <p style={{ fontSize: 12.5, fontWeight: 600 }}>{new Date(timestamp).toLocaleString()}</p>
          </div>
        </div>
        <hr className="divider" />

        <ReportSection title="Patient Information">
          <div className="grid grid-4">
            <ReportField label="Name" value={patient.name || "Unnamed Patient"} />
            <ReportField label="Patient ID" value={patient.patientId || "—"} />
            <ReportField label="Age" value={`${patient.age} yrs`} />
            <ReportField label="Gender" value={patient.gender} />
          </div>
        </ReportSection>

        <ReportSection title="Prediction Summary">
          <div className="grid grid-4">
            <ReportField label="Prediction" value={<PredictionBadge prediction={result.prediction} />} />
            <ReportField label="Probability" value={`${(result.probability * 100).toFixed(1)}%`} />
            <ReportField label="Risk Level" value={<RiskBadge level={result.riskLevel} />} />
            <ReportField label="Attending Clinician" value={user?.name || "—"} />
          </div>
        </ReportSection>

        <ReportSection title="Top SHAP Features">
          <FeatureMiniTable rows={topShap.map((f) => ({ label: f.label, value: f.value }))} accent="var(--shap)" />
        </ReportSection>

        <ReportSection title="Top LIME Features">
          <FeatureMiniTable rows={topLime.map((f) => ({ label: f.label, value: f.value }))} accent="var(--lime)" />
        </ReportSection>

        <ReportSection title="Unified Ranking">
          <FeatureMiniTable rows={unified.ranking.slice(0, 6).map((f) => ({ label: `#${f.rank} ${f.label}`, value: f.unified }))} accent="var(--unified)" />
        </ReportSection>

        <ReportSection title="Reliability Scores">
          <div className="grid grid-2">
            <ReportField label="Agreement Score" value={`${unified.agreementScore.toFixed(1)}%`} />
            <ReportField label="Confidence Score" value={`${unified.confidenceScore.toFixed(1)}%`} />
          </div>
        </ReportSection>

        <ReportSection title="Final Unified Explanation" last>
          <p style={{ fontSize: 13, lineHeight: 1.75, color: "var(--ink-soft)", background: "var(--surface-tint)", padding: 16, borderRadius: 10 }}>
            {summary}
          </p>
        </ReportSection>

        <div className="print-only" style={{ marginTop: 24, fontSize: 10.5, color: "var(--muted)" }}>
          This report was generated by UnifyXAI-Med for clinical decision support. It is not a diagnostic
          document and must be reviewed by a licensed healthcare professional.
        </div>
      </div>
    </Layout>
  );
}

function ReportSection({ title, children, last }) {
  return (
    <div style={{ marginBottom: last ? 0 : 22 }}>
      <h4 style={{ fontSize: 12.5, textTransform: "uppercase", letterSpacing: "0.06em", color: "var(--blue-700)", marginBottom: 10, fontWeight: 700 }}>
        {title}
      </h4>
      {children}
    </div>
  );
}

function ReportField({ label, value }) {
  return (
    <div>
      <p style={{ fontSize: 11, color: "var(--muted)" }}>{label}</p>
      <p style={{ fontSize: 13.5, fontWeight: 600, marginTop: 3 }}>{value}</p>
    </div>
  );
}

function FeatureMiniTable({ rows, accent }) {
  return (
    <div className="table-wrap">
      <table className="table">
        <tbody>
          {rows.map((r, i) => (
            <tr key={i}>
              <td style={{ fontWeight: 600, width: "60%" }}>{r.label}</td>
              <td className="mono" style={{ color: r.value >= 0 ? "var(--red-600)" : "var(--green-600)" }}>
                {r.value >= 0 ? "+" : ""}{r.value.toFixed(3)}
              </td>
              <td style={{ width: "30%" }}>
                <div className="progress-track">
                  <div className="progress-fill" style={{ width: `${Math.min(100, Math.abs(r.value) * 140)}%`, background: accent }} />
                </div>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
